title: Docky
description: Docky is a library to create frontend-first APIs in minutes
theme: just-the-docs

url: https://oegea.github.io/docky

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
